### ISSUE TITLE
JUnitViewTest failing with Mars

### ISSUE THREAD

**Issue by jpeterka** [jboss-reddeer/reddeer#1024] opened 2015-04-08 09:27 UTC
http://machydra.brq.redhat.com:8080/job/RedDeer_verification_matrix_report/904/artifact/reddeermatrixtestresults.html

**Comment by apodhrad** [comment] 2015-07-03 14:00
Caused by https://bugs.eclipse.org/bugs/show_bug.cgi?id=468948

**Comment by apodhrad** [comment] 2015-07-09 09:08
Fixed by #1131

**Closed by apodhrad** 2015-07-09 09:08 UTC
Labels: bug
