### ISSUE TITLE
RedDeer should be installed without dependency complains

### ISSUE THREAD

**Issue by jpeterka** [jboss-reddeer/reddeer#1140] opened 2015-07-13 09:33 UTC
Step: Install Eclipse
Step: Add RedDeer update site and try to install all content
Assert: No dependency issues should arise and installation should pass

**Comment by mmalina** [comment] 2015-07-14 08:31
This is a duplicate of #1139 . But to make you happy, I will close it when that one is done.

**Closed** 2015-07-15 10:49 UTC
Labels: task
