### ISSUE TITLE
Slow test execution on OSX slave

### ISSUE THREAD

**Issue by jpeterka** [jboss-reddeer/reddeer#1325] opened 2015-12-07 10:51 UTC
http://machydra.brq.redhat.com:8080/job/RedDeer_master_matrix_report/514/artifact/reddeermastermatrixtestresults.html

This time: zamek

**Comment by mmalina** [comment] 2015-12-07 15:26
It seems that zamek is now even slower than it used to be. On domek the test is finished in around 1 hr 50 min. On zamek, 140 min is not enough and then it times out. I was not able to find out the cause of this. As an immediate measure I removed the stable-mac label from zamek.

**Comment by jpeterka** [comment] 2015-12-10 14:54
Strange, it seems we have two various issues here: 
1) tests are frozen during execution and timeouts (#1328)
2) tests are processing but very slow and timeouts

**Comment by mmalina** [comment] 2015-12-10 16:00
OK, so this is a duplicate of long standing issue #1174 . Closing.

**Comment by mmalina** [comment] 2015-12-14 13:24
I created an internal JIRA to reinstall zamek to see if that helps because I ran out of other ideas. Tracked in JBQA-12583 . Closing this issue.

**Closed** 2015-12-14 13:45 UTC
Labels: blocker, bug
