### ISSUE TITLE
When AbstractEditor is active but not focused, should focus

### ISSUE THREAD

**Issue by odockal** [jboss-reddeer/reddeer#1469] opened 2016-09-02 14:15 UTC
sometimes, it happens that TextEditor is active but not focused and work with editor fails on WaitTimeoutException when calling contentAssistant for example.

**Comment by rawagner** [comment] 2016-09-06 08:10
can you attach stack trace ?

**Comment by odockal** [comment] 2016-09-06 11:48
I played around a bit and found out that it seems like a problem from derived implementation of TextEditor class used in problematic jbosstools plugin. I will try to dig around more.

**Comment by odockal** [comment] 2016-09-06 15:14
I made a [jira](https://issues.jboss.org/browse/JBIDE-23132) for this issue, probably it is from upstream.

**Comment by rawagner** [comment] 2016-12-20 20:54
not a bug in RD then, closing

**Closed by rawagner** 2016-12-20 20:54 UTC
Labels: bug, upstream
