### ISSUE TITLE
Update stable RedDeer location to a new update site URL schema

### ISSUE THREAD

**Issue by jpeterka** [jboss-reddeer/reddeer#1111] opened 2015-06-24 08:44 UTC
Stable sites should comply with #1110

**Comment by jpeterka** [comment] 2015-06-24 12:36
Just for an illustration, we should follow Eclipse update site conventions as possible:

https://wiki.eclipse.org/Eclipse_Project_Update_Sites

or for example SWTBot update sites are constructed following way"
http://download.eclipse.org/technology/swtbot/releases/latest/
http://download.eclipse.org/technology/swtbot/snapshots

I'm aware that RedDeer bits are now located on jboss.org under jboss tools so we should comply with that but if possible update sites URL should be constructed as close as possible to Eclipse/SWTBot way.

**Comment by nickboldt** [comment] 2015-06-24 16:02
For consistency, I've moved updates/development/core/reddeer/0.8.0.M1 into http://download.jboss.org/jbosstools/updates/development/luna/core/reddeer/ and removed duplicate 0.8.0.m1 (why lowercase?) folder.

**Comment by nickboldt** [comment] 2015-06-24 16:34
So, I've updated your job to use a publishingPath variable, which you can set at build time to push bits to the Luna path or the Mars one.

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/RedDeer_master/jobConfigHistory/showDiffFiles?timestamp1=2015-06-23_23-56-14&timestamp2=2015-06-24_12-14-40

Also updated this PR ( https://github.com/jboss-reddeer/reddeer/pull/1110 )to show the two options (and default to the Luna one for now).

**Comment by nickboldt** [comment] 2015-06-24 16:40
And finally, I've moved your latest builds from /snapshots/builds/ into http://download.jboss.org/jbosstools/builds/staging/RedDeer_master/ so you're at least consistent w/ one convention.

If you prefer to move to http://download.jboss.org/jbosstools/mars/snapshots/builds/RedDeer_master/ I can make that happen.

Once my PR is merged, I can remove the Eclipse-unversioned /snapshots/builds/ folder.

**Comment by maxandersen** [comment] 2015-06-25 08:59
guys - we have a very clear and specific way for our updatesites and it is fully compliant with eclipse.
That is what we should use in our builds that *uses* reddeer.

if you guys want *separate* schema for reddeer where you host *multiple* versions of reddeer that work with *multiple* versions of Eclipse then lets look at that.

Are you really planning on ensuring you work with multiple versions of eclipse ?

I assume you will only build against one TP (i.e. Luna) and then test against multiple versions ? then why not just use the /luna/* based schema for that ?

And no matter what - you need to make sure that none of your updates have associate sites or references to *any* eclipse content since otherwise you will end up "infecting" downstream builds wit those dependencies. 

And then we'll need to mirror and strip reddeer like we do for any eclipse site today since eclipse is not enforcing this.

and if we are moving anything then let at least fix it so it does not use mixed case and just becomes reddeer and not RedDeer in the url.

**Comment by maxandersen** [comment] 2015-06-25 09:00
and no, you cannot use snapshots as  place for releases that are used in JBoss Tools releases, snapshots are only  milestones and/or intermediate builds. 

snapshots should be possible to delete/replace at any time.

**Comment by mmalina** [comment] 2015-06-25 09:06
@maxandersen let wait for Jirka, but I think he now agrees with the paths that Nick suggested.
But regarding snapshots/milestones for JBoss Tools releases, what about this:
http://download.jboss.org/jbosstools/updates/development/luna/core/reddeer/0.8.0.M1/
That should be ok, no? Alternatively we could release a minor release for this, but this seems much easier and a URL like this should be permanent.

**Comment by maxandersen** [comment] 2015-06-25 09:15
Just to explain the "mapping":

```
/updates/4.5milestones  -> /mars/development/updates
/updates/4.5-I-builds  -> /mars/staging/updates
/updates/4.5-N-builds -> /mars/snapshots/updates
/updates/4.5 -> /mars/stable/updates
````
so please just use jbosstools conventions so we get consistency and *once* you move to eclipse and only then we incur the overhead it will be to have to mirror reddeer for its use.

**Comment by jpeterka** [comment] 2015-06-25 10:45
Yeah, I'm ok with the suggested approach. 

@maxandersen, two things:
* not sure what you mean by snapshots here - I expect RedDeer milestone (http://download.jboss.org/jbosstools/updates/development/luna/core/reddeer/0.8.0.M1/ ) can be considered as a regular release  even it's not final still I expect it as constant stable not removable update site which allows usage for all downstream projects all the time without any changes. Is my understanding correct?

* "And no matter what - you need to make sure that none of your updates have associate sites or references to any eclipse content since otherwise you will end up "infecting" downstream builds wit those dependencies" -- I agree. Of course every testing framework "somehow infects" tested product  (maybe with the exception of JUnit which is already included). In terms of associated update sites RedDeer uses SWTBot to get SWTBot generator feature which should be harmless for downstream. Soon we will cut it so only Eclipse update site is the only upstream update site for RedDeer. Should be ok for JBT, yes?

**Comment by jpeterka** [comment] 2015-06-25 13:08
To summarize it I'm quite ok with any suggestions as far as it doesn't contain unnecessary segments for us (like core, etc.) and will be persistent in the future. Concern of this issue was mainly to be consistent across all RedDeer update sites. My top choice still would be something simple like this:

Stable frozen release builds without further updates (these would be used for JBT releases to assure reproducible JBT test builds):
http://download.jboss.org/jbosstools/reddeer/release/0.8
http://download.jboss.org/jbosstools/reddeer/release/0.8.M1

Updatable development site:
http://download.jboss.org/jbosstools/reddeer/updates/master

We don't need anything special beyond this.

**Comment by nickboldt** [comment] 2015-06-25 13:36
Several problems come to mind with the last suggestion.

a) we use "stable" not "release"
b) a milestone build is not "stable", it's "development"
c) you use "release" to mean "updates" but then use "updates/master" for snapshots? That's hella inconsistent.
d) you're still not defining which version of Eclipse you support

What about this?

http://download.jboss.org/jbosstools/mars/stable/updates/reddeer/ (latest releases)
http://download.jboss.org/jbosstools/mars/development/updates/reddeer/ (latest milestones)
http://download.jboss.org/jbosstools/mars/snapshots/updates/reddeer/ (only the latest snapshot)
plus
http://download.jboss.org/jbosstools/mars/snapshots/builds/RedDeer_master/ (all recent CI builds)

or... maybe you want to just release into Nexus, like Locus does?

**Comment by jpeterka** [comment] 2015-06-25 13:53
@nickboldt: Thanks Nick, I think we can keep current update site schema after all (although it's still misleading  to me - especially usage of "updates" and "snapshots" I would expect quite reverse). Current locations are these:
http://download.jboss.org/jbosstools/updates/development/luna/core/reddeer/0.8.0.M1/
http://download.jboss.org/jbosstools/mars/snapshots/builds/RedDeer_master/

**Comment by mmalina** [comment] 2015-06-25 13:56
@nickboldt It seems a bit counter-intuitive to us to use "updates" for something that actually doesn't change - stable releases. I mean if you take the full path including the version that we usually use. But if you take that away and use it for the latest, then it makes more sense.

**Comment by nickboldt** [comment] 2015-06-25 15:00
http://download.jboss.org/jbosstools/mars/snapshots/builds/RedDeer_master/ contains individual *snapshot* *builds*. Hence, /snapshots/builds/. (I agree that since you build against Luna the /mars/ segment is a bit misleading.

@mmalina @jpeterka  Would you prefer /luna/snapshots/builds/ ? I could make that folder a symlink back into http://download.jboss.org/jbosstools/builds/staging/ where all the Luna (and earlier) builds were located.

---

Meanwhile, /updates/*/luna/*/reddeer/ [1] contains all the updates for Luna, starting with 0.8.0.M1 (and all future milestones you publish there).

[1] http://download.jboss.org/jbosstools/updates/development/luna/core/reddeer/ 

So, to end-users, you can give out [1], since it need not change as you release more milestones. This is the same approach that JBT and JBDS uses - a static, unchanging URL which composites the ACTUAL bits behind a different URL.

**Comment by nickboldt** [comment] 2015-06-25 15:04
Note that I'd be happy to move your bits from http://download.jboss.org/jbosstools/updates/development/luna/core/reddeer/ into http://download.jboss.org/jbosstools/updates/development/luna/reddeer/ if you'd like. See also https://issues.jboss.org/browse/JBIDE-20151 for new tool you can use to more easily publish bits.

**Comment by mmalina** [comment] 2015-06-25 15:04
@nickboldt RedDeer is building against mars since yesterday or today, so that's fine now :)
As to the other part, yes, I agree that without the specific version at the end, it really contains continuous updates. But our typical use for RedDeer is to use an exact specific version number to be used for JBoss Tools Integration Tests (that's the requirement raised my Max - to have something non-moving, for build reproducibility).

**Comment by maxandersen** [comment] 2015-06-26 08:19
guys, 

its called "updates" because it is an updatesite. Not sure why that is a problem. 

Here i'm leaving out the reddeer part just to keep it simple.

we have a site at `updates/development` too which one uses to not have to have a version specific string

`updates/development/0.8.0.M1` is only created *once* and stays as long as needed but in theory should be okey to remove once `updates/stable/0.8.0.Final` gets created.

Please point out what is inconsistent in this. This is actually more consistent and reliable than what is at eclipse.org.

And no, even eclipse.org updatesites is not something we want at all in our updatesites that are used in builds.  We don't even want jboss.org ones.

We want to avoid mixing/leaking dependencies into the build chain.

This pattern is what we've been using for a loong time in jbosstools - I know at time we send mails that uses what I call internal urls instead of these more public/consistent urls but that is what we want to get away from by having everything we have follow this same pattern that allows for anyone to use either very version specific content or say "I just want the latest of either stable, development or snapshots (aka. nightly)

If you are building against 'mars' then you should be in the `mars` stream, *not* luna.

Luna builds can point to the `mars` stuff just as fine as mars can point to luna - but lets make it consistent that we are not mixing in mars stuff into luna and since we are *not* referencing external sites from our build sites (as mentioned above) these should be safe to use across streams *assuming* you actually test it against both luna and mars.

**Comment by maxandersen** [comment] 2015-06-26 08:21
@nickboldt please don't suggest "Would you prefer /luna/snapshots/builds/" we have a pattern we use; don't create new conventions when we already have one that does exactly the same please.  

If there is an issue it our naming scheme we should fix that consistently, not introduce reddeer specific symoblic link workarounds that needs maintaining.

**Comment by maxandersen** [comment] 2015-06-26 08:25
btw. i suggest we have a quick call on monday and just go over this since it seems we got 3 different conventions currently active in reddeer where there should only be jboss tools one. 

And if reddeer would just follow that convention luna would stop being updated from now on, and just adapt the new cleaner name and publish scheme we use for mars stream.

And please, the stream name is about what target platform it uses - it is perfectly fine it supports previous versions too but that is a separate concern. Only if you need two different builds would you publish to both mars and luna streams.

**Comment by mmalina** [comment] 2015-06-26 08:37
Hey @maxandersen , I think we've already settled on the part about the url - yes, Nick suggested the ad hoc luna/snapshots/builds, but since RedDeer moved to use mars for build a few days ago, this is now irrelevant. Originally @jpeterka wanted a url that would not include mars or luna, but I think Nick has successfully talked him out of it :)

So it seems you don't have a problem for us to use milestones (such as updates/development/0.8.0.M1) in jbosstools-integration-tests, cool.

I think we're still not clear on what you mean by adding upstream update sites:
"And no, even eclipse.org updatesites is not something we want at all in our updatesites that are used in builds."
You mean if RedDeer update site contains reference to another update site, that would be wrong? We don't do that.
Currently, during build, we use swt bot update site and bundle some plugins from there into our update site. The resulting update site doesn't reference any other update site. Is that ok or not?

You say "updates" means update site, so it's clear. So what does "builds" mean then? It's an update site also. So when I see that we have two - updates and builds - without knowing I would assume that builds contains update sites of specific builds and updates contains moving update sites. But no need to discuss this - it's more or less clear to me how we use it now. I'm just explaining what we meant by "potentially unintuitive" previously ;)

Monday call sounds fine.

**Comment by maxandersen** [comment] 2015-06-26 08:41
if you look into http://download.jboss.org/jbosstools/mars/snapshots/builds/ folders i.e. http://download.jboss.org/jbosstools/mars/snapshots/builds/RedDeer_master/2015-06-23_09-53-33-B635/ you will notice these are not *only* updatesites, they are all the build artifacts (logs and other things).

updates -> updatesites (without version they change, with version they dont change)

builds -> all stuff that a build produces. its basically output of jenkins job. i.e. jbds installer has a builds folder, but no updates since jbds installer is not producing an updatesite anyone uses.

**Comment by jpeterka** [comment] 2015-06-26 10:45
Guys, thanks for the explanation. Now it makes more sense to me. So if I understood it correctly this could be a widely acceptable summary: Let's follow current JBT hierarchy, don't create another style.  Just remove unnecessary fragments like "core" if possible from RedDeer update site. Except that it should be ok. More radical changes would not be good as they would interfere with current JBT schema.

**Comment by nickboldt** [comment] 2015-06-26 14:36
If we all agree, can we merge https://github.com/jboss-reddeer/reddeer/pull/1115 ? 

I'd like to have your stuff stop being published into the wrong place. snapshots/builds/${JOB_NAME}/ is not authorized based on the conversation above.

**Comment by mmalina** [comment] 2015-06-26 15:52
+1, @jpeterka please merge.

**Comment by nickboldt** [comment] 2015-06-30 15:03
Because Max takes exception to the use of upper case letters in paths, job https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/RedDeer_master/ is now https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/reddeer_master/ but Jenkins doesn't seem to respect renaming jobs simply for case changes, so instead I updated the config to use 

    publishingPath	 = "mars/snapshots/builds/reddeer_master/${BUILD_ID}-B${BUILD_NUMBER}/all/repo/" 

instead of 

    publishingPath	 = "mars/snapshots/builds/${JOB_NAME}/${BUILD_ID}-B${BUILD_NUMBER}/all/repo/" 

So, your latest builds will now here:

http://download.jboss.org/jbosstools/mars/snapshots/builds/reddeer_master/

**Comment by mmalina** [comment] 2015-07-01 08:18
Thanks a lot, @nickboldt for all the work. So I think this issue can be closed now, do you agree @jpeterka ?

**Comment by mmalina** [comment] 2015-07-01 11:59
No objection from @jpeterka , so closing.

**Closed by mmalina** 2015-07-01 11:59 UTC
Labels: task
