### ISSUE TITLE
TreeHandler can cause Exception during sync execution in UI thread

### ISSUE THREAD

**Issue by jpeterka** [jboss-reddeer/reddeer#817] opened 2014-09-11 15:37 UTC
cat target/surefire-reports/org.jboss.tools.mylyn.ui.bot.test.MylynSuite.txt
-------------------------------------------------------------------------------
Test set: org.jboss.tools.mylyn.ui.bot.test.MylynSuite
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 68.019 sec <<< FAILURE!
testAuthServer default(org.jboss.tools.mylyn.ui.bot.test.MylynTestJenkins)  Time elapsed: 22.996 sec  <<< ERROR!
org.jboss.reddeer.swt.exception.SWTLayerException: Exception during sync execution in UI thread
    at org.jboss.reddeer.swt.util.Display.syncExec(Display.java:75)
    at org.jboss.reddeer.swt.handler.TreeHandler.getItems(TreeHandler.java:59)
    at org.jboss.reddeer.swt.impl.tree.AbstractTree.getItems(AbstractTree.java:47)
    at org.jboss.reddeer.swt.impl.tree.TreeHasChildren.test(DefaultTreeItem.java:351)
    at org.jboss.reddeer.swt.wait.WaitUntil.stopWaiting(WaitUntil.java:55)
    at org.jboss.reddeer.swt.wait.AbstractWait.wait(AbstractWait.java:106)
    at org.jboss.reddeer.swt.wait.AbstractWait.<init>(AbstractWait.java:75)
    at org.jboss.reddeer.swt.wait.AbstractWait.<init>(AbstractWait.java:51)
    at org.jboss.reddeer.swt.wait.AbstractWait.<init>(AbstractWait.java:39)
    at org.jboss.reddeer.swt.wait.WaitUntil.<init>(WaitUntil.java:23)
    at org.jboss.reddeer.swt.impl.tree.DefaultTreeItem.findTreeItem(DefaultTreeItem.java:242)
    at org.jboss.reddeer.swt.impl.tree.DefaultTreeItem.findTreeItem(DefaultTreeItem.java:301)
    at org.jboss.reddeer.swt.impl.tree.DefaultTreeItem.findTreeItem(DefaultTreeItem.java:328)
    at org.jboss.reddeer.swt.impl.tree.DefaultTreeItem.<init>(DefaultTreeItem.java:107)
    at org.jboss.reddeer.swt.impl.tree.DefaultTreeItem.<init>(DefaultTreeItem.java:50)
    at org.jboss.tools.mylyn.ui.bot.test.MylynTestJenkins.testAuthServer(MylynTestJenkins.java:116)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.jboss.reddeer.junit.internal.runner.RequirementsRunner$InvokeMethodWithException.evaluate(RequirementsRunner.java:275)
    at org.jboss.reddeer.junit.internal.runner.RunAfters.evaluate(RunAfters.java:43)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.jboss.reddeer.junit.internal.runner.FulfillRequirementsStatement.evaluate(FulfillRequirementsStatement.java:26)
    at org.jboss.reddeer.junit.internal.runner.RunAfters.evaluate(RunAfters.java:43)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.jboss.reddeer.junit.internal.runner.RequirementsRunner.run(RequirementsRunner.java:112)
    at org.junit.runners.Suite.runChild(Suite.java:127)
    at org.junit.runners.Suite.runChild(Suite.java:26)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runners.Suite.runChild(Suite.java:127)
    at org.junit.runners.Suite.runChild(Suite.java:26)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
    at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
    at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:123)
    at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:87)
    at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.runTests(AbstractUITestApplication.java:44)
    at org.eclipse.e4.ui.internal.workbench.swt.E4Testable$1.run(E4Testable.java:73)
    at java.lang.Thread.run(Thread.java:744)
Caused by: org.eclipse.swt.SWTException: Widget is disposed
    at org.eclipse.swt.SWT.error(SWT.java:4441)
    at org.eclipse.swt.SWT.error(SWT.java:4356)
    at org.eclipse.swt.SWT.error(SWT.java:4327)
    at org.eclipse.swt.widgets.Widget.error(Widget.java:476)
    at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:413)
    at org.eclipse.swt.widgets.Tree.getItems(Tree.java:1585)
    at org.jboss.reddeer.swt.handler.TreeHandler$1.run(TreeHandler.java:64)
    at org.jboss.reddeer.swt.handler.TreeHandler$1.run(TreeHandler.java:1)
    at org.jboss.reddeer.swt.util.Display$ErrorHandlingRunnable.run(Display.java:139)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:136)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3806)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3444)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
    at org.eclipse.tycho.surefire.osgibooter.UITestApplication.runApplication(UITestApplication.java:31)
    at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.run(AbstractUITestApplication.java:115)
    at org.eclipse.tycho.surefire.osgibooter.UITestApplication.start(UITestApplication.java:37)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:382)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:236)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
testServer default(org.jboss.tools.mylyn.ui.bot.test.MylynTestJenkins)  Time elapsed: 43.107 sec[ldimaggi@ldimaggi org.jboss.tools.mylyn.ui.bot.test]$

**Comment by ljelinkova** [comment] 2015-02-23 12:41
When you look into the stack trace there is: Caused by: org.eclipse.swt.SWTException: Widget is disposed. When you create a new build server a new shell opens therefore you need to activate (or open) the MylynBuildView again. It is a recommended practice to put call to activate() method into every method inside your view (also to createBuildServer). 

I am closing this issue since it is not a bug in Red Deer.

**Closed by ljelinkova** 2015-02-23 12:41 UTC
Labels: bug
